/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Radnik;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import kontroler.Kontroler;
import sesija.Sesija;
import start.KlijentStart;

/**
 *
 * @author Nina777
 */
public class Glavna extends javax.swing.JFrame {

    /**
     * Creates new form Glavna
     */
    Kontroler k;

    public Glavna() {
        initComponents();
        k = new Kontroler();
        new KlijentStart().start();
//        Sluzbenik ulogovani = (Sluzbenik) Sesija.vratiInstancu().getMapa().get("sluzbenik");
        Radnik ulogovani = (Radnik) Sesija.vratiInstancu().getMapa().get("radnik");
        if (ulogovani != null) {
//            jMenuBar1.setVisible(true);
            new FormaRepertoar().setVisible(true);
        } else {
//            jMenuBar1.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIme = new javax.swing.JTextField();
        jtfSifra = new javax.swing.JTextField();
        btnPrijava = new javax.swing.JButton();
        jlPrijava = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijava");

        jLabel1.setText("Korisničko ime:");

        jLabel2.setText("Korisnička šifra:");

        btnPrijava.setText("Prijavi se");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        jlPrijava.setText("Prijavite se u vaš korisnički nalog!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlPrijava)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrijava)
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addComponent(jtfIme)
                    .addComponent(jtfSifra))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jlPrijava)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnPrijava)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        // TODO add your handling code here:
//        String username = jtxtUsername.getText().trim();
//        String password = jtxtPassword.getText().trim();
//        Sluzbenik s = new Sluzbenik(0, "", "", username, password);
//        try {
//            Sluzbenik ulogovani  = k.prijaviKorisnika(s);
//            if(ulogovani!=null){
//                Sesija.vratiInstancu().getMapa().put("sluzbenik", ulogovani);
//                jtxtPassword.setText("");
//                jtxtUsername.setText("");
//                jtxtPassword.setVisible(false);
//                jtxtUsername.setVisible(false);
//                jLabel1.setVisible(false);
//                jLabel2.setVisible(false);
//                jlblStatus.setText("Sluzbenik je uspesno prijavljen.");
//                jMenuBar1.setVisible(true);
//                jbtnPrijaviSe.setVisible(false);
//            } else {
//                jlblStatus.setText("Sistem ne moze da pronadje sluzbenika.");
//            }
//        } catch (IOException ex) {
//            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
//        }

        String korisnickoIme = jtfIme.getText().trim();
        String sifra = jtfSifra.getText().trim();
        Radnik r = new Radnik(0, "", "", korisnickoIme, sifra);

        try {
            Radnik ulogovani = k.prijaviKorisnika(r);
            if (ulogovani != null) {
                Sesija.vratiInstancu().getMapa().put("radnik", ulogovani);
                jtfIme.setText("");
                jtfSifra.setText("");
                jtfIme.setVisible(false);
                jtfSifra.setVisible(false);
                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                jlPrijava.setText("Radnik je uspešno prijavljen.");
                btnPrijava.setVisible(false);
                FormaRepertoar frmRep = new FormaRepertoar();
                frmRep.setVisible(true);
                         this.setVisible(false);
                
            } else {
                jlPrijava.setText("Sistem ne može da pronađe službenika.");
            }
        } catch (IOException ex) {
            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrijavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Glavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlPrijava;
    private javax.swing.JTextField jtfIme;
    private javax.swing.JTextField jtfSifra;
    // End of variables declaration//GEN-END:variables
}
